In [1]:
import numpy as np

In [9]:
a = np.array([0,1,2,3,4,5,6,7,8])
print(a)

[0 1 2 3 4 5 6 7 8]


In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [15]:
l = range(1000)
%timeit [i**2 for i in l]

698 µs ± 130 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
a = np.arange(1000)
%timeit a**2

8.69 µs ± 326 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a.ndim

1

In [23]:
a.shape

(11,)

In [25]:
len(a)

11

In [26]:
b = np.array([[0,1,2,],[0,1,2]])

In [28]:
b.ndim

2

In [29]:
b.shape

(2, 3)

In [30]:
len(b)

2

In [31]:
c = np.array([[0,1],[2,3],[4,5],[6,7]])
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [32]:
c.ndim

2

In [33]:
c.shape

(4, 2)

In [34]:
len(c)

4

In [36]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [44]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a = np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [56]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [57]:
np.diag(a)

array([1, 2, 3, 4])

In [61]:
a = np.random.rand(5)
a

array([0.22795459, 0.45463461, 0.09165905, 0.77537331, 0.71166455])

In [62]:
a = np.random.randn(5)
a

array([-0.78590363,  0.9328683 ,  1.23952066, -2.47480472, -0.01091187])

In [63]:
a = np.arange(10)
a.dtype

dtype('int32')

In [65]:
a = np.arange(10,dtype="float32")
a.dtype
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [67]:
a = np.zeros((3,3))
a
a.dtype

dtype('float64')

In [69]:
a = np.array([1+2j, 2+4j])
print(a.dtype)
a

complex128


array([1.+2.j, 2.+4.j])

2. Numerical operations on Numpy-