In [2]:
import numpy as np

In [9]:
a = np.array([0,1,2,3,4,5,6,7,8])
print(a)

[0 1 2 3 4 5 6 7 8]


In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [15]:
l = range(1000)
%timeit [i**2 for i in l]

698 µs ± 130 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
a = np.arange(1000)
%timeit a**2

8.69 µs ± 326 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a.ndim

1

In [23]:
a.shape

(11,)

In [25]:
len(a)

11

In [26]:
b = np.array([[0,1,2,],[0,1,2]])

In [28]:
b.ndim

2

In [29]:
b.shape

(2, 3)

In [30]:
len(b)

2

In [31]:
c = np.array([[0,1],[2,3],[4,5],[6,7]])
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [32]:
c.ndim

2

In [33]:
c.shape

(4, 2)

In [34]:
len(c)

4

In [36]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [44]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a = np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [56]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [57]:
np.diag(a)

array([1, 2, 3, 4])

In [61]:
a = np.random.rand(5)
a

array([0.22795459, 0.45463461, 0.09165905, 0.77537331, 0.71166455])

In [62]:
a = np.random.randn(5)
a

array([-0.78590363,  0.9328683 ,  1.23952066, -2.47480472, -0.01091187])

In [63]:
a = np.arange(10)
a.dtype

dtype('int32')

In [65]:
a = np.arange(10,dtype="float32")
a.dtype
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [67]:
a = np.zeros((3,3))
a
a.dtype

dtype('float64')

In [69]:
a = np.array([1+2j, 2+4j])
print(a.dtype)
a

complex128


array([1.+2.j, 2.+4.j])

2. Numerical operations on Numpy-

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
b = np.ones(10) + 1
a - b

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [14]:
a * b

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [16]:
c = np.diag([1,2,3,4])

print(c * c)
print("********************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [17]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])

a == b

array([False,  True, False,  True])

In [18]:
a > b

array([False, False,  True, False])

In [20]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a, b)

False

In [22]:
np.array_equal(a, c)

True

In [23]:
#Logical Operators

In [27]:
a = np.array([1,1,0,0], dtype =bool)
b = np.array([1,0,1,0], dtype =bool)

np.logical_or(a, b)


array([ True,  True,  True, False])

In [26]:
np.logical_and(a, b)

array([ True, False, False, False])

In [28]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.log(a)

C:\Users\piyus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [30]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
#Shape Mismatc

In [33]:
a = np.arange(4)
a + np.arange([1,2])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [34]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [35]:
x.argmin()

0

In [38]:
 data = np.loadtxt("S:/course/AppliedAI-Machine-Learning-Online-Course/Module 1 _ Fundamentals of Programming/5. Python for Data Science_ Numpy/1.1. All datasets and notes/numpy/populations.txt")

In [39]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [43]:
data.shape


2

In [44]:
data.ndim

2

In [45]:
year,hares,lynxes,carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [46]:
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [47]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [48]:
np.argmax(population,axis =1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [49]:
#Broad casting

In [50]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [55]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)

print("********************************")

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
********************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [51]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [54]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [58]:
a =  np.arange(0,40,10)
a.shape

(4,)

In [59]:
a = a[:, np.newaxis]
a.shape 

(4, 1)

In [60]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [61]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [62]:
#ARRAY SHape manipulation

In [63]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [64]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [71]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [73]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [75]:
b = a.reshape((2,3))
print(b)

[[1 2 3]
 [4 5 6]]


In [77]:
b =b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
b [0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [80]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [81]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [82]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [83]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [84]:
a[0,2,1]

5

In [85]:
a[0,2,1]

5

In [87]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [88]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [94]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [97]:
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [98]:
a[j]

array([1, 2, 3, 4])